---
- name: src-host - Shut down prysm-docker-compose
  shell: "docker-compose down"
  args:
    chdir: "{{ prysm_install_path }}"
  when: inventory_hostname == 'to_upgrade'

- name: src-host - Get current branch
  shell: "git rev-parse --abbrev-ref HEAD"
  args:
    chdir: "{{ prysm_install_path }}"
  register: current_branch
  when: inventory_hostname == 'to_upgrade'
  
- name: src-host - You are not on master branch!
  debug:
    msg: You are not on master branch, but on this branch {{ current_branch.stdout }}"
  when: inventory_hostname == 'to_upgrade' and current_branch.stdout != 'master'

- name: src-host - git stash (save changes)
  shell: "git stash"
  args:
    chdir: "{{ prysm_install_path }}"
  when: inventory_hostname == 'to_upgrade'

- name: src-host - Pull git
  shell: "git pull"
  args:
    chdir: "{{ prysm_install_path }}"
  register: pull_result
  when: inventory_hostname == 'to_upgrade'

- name: src-host - Git pull result
  debug:
    msg: "{{ pull_result.stdout }}"
  when: inventory_hostname == 'to_upgrade'

- name: src-host - Pop stash
  shell: "git stash pop"
  args:
    chdir: "{{ prysm_install_path }}"
  register: pop_result
  when: inventory_hostname == 'to_upgrade'
  ignore_errors: yes

- name: src-host - Check for errors by pop
  fail:
    msg: "There are not expected errors: {{ pop_result }}"
  when: inventory_hostname == 'to_upgrade' and pull_result.stderr != "No stash entries found." and pull_result.stderr != ""