---
- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - build-essential
    - gcc
    - golang
  become: yes

- name: Install ethdo
  shell: GO111MODULE=on go get github.com/wealdtech/ethdo

- name: Add ethdo to PATH
  blockinfile:
    path: "~/.profile"
    block: |
      if [ -d "$HOME/go/bin" ] ; then
        PATH="$PATH:$HOME/go/bin"
      fi